# This is a basic workflow to help you get started with Actions

name: Test build on pull request

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: dmlex-v1.0/specification

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages for XML and JSON validation
        run: |
          pip install xmlschema jsonschema xmlstarlet pyshacl
      - name: Validate
        run: make validate_xml validate_json validate_rdf
  build:
    needs: validate
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get update
          sudo apt-get install xsltproc fop xmlstarlet ttf-mscorefonts-installer graphviz libxml2-utils
          sudo fc-cache -f
      - name: Make XML, HTML and PDF
        run: make html pdf
